---
- name: stop plex service
  systemd:
    name: plexmediaserver
    state: stopped
    
- name: restore from nas
  unarchive:
    src: {{ restore_src }}
    dest: /var/lib/plexmediaserver/Library/Application Support
    remote_src: true

- name: start plex service
  systemd:
    name: plexmediaserver
    state: started
...
